# Generated by Django 4.1.5 on 2023-01-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('ish_vaqti', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('sahifa', models.PositiveSmallIntegerField()),
                ('janr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('trik', models.CharField(choices=[('ha', 'ha'), ('yo`q', 'yo`q')], max_length=30, null=True)),
                ('kitob_soni', models.PositiveIntegerField()),
                ('jinsi', models.CharField(choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10)),
                ('tugilgan_sanasi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('bitiruvchi', models.CharField(max_length=10)),
                ('kitoblar_soni', models.PositiveSmallIntegerField(default=0)),
                ('kursi', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olingan_sana', models.DateTimeField()),
                ('qaytarish_sanasi', models.DateTimeField()),
                ('qaytardi', models.CharField(choices=[('ha', 'ha'), ('yo`q', 'yo`q')], max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.admin')),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.kitob')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.talaba')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asosiy.muallif'),
        ),
    ]
