# Generated by Django 4.1.5 on 2023-01-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='admin',
            new_name='Admin',
        ),
    ]
