# Generated by Django 4.1.5 on 2023-01-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_rename_admin_record_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='ish_vaqti',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sanasi',
            field=models.DateField(),
        ),
    ]
